# Generated by Django 4.1.7 on 2023-03-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoveeregistrationtwo', '0004_student_city_student_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='county',
            new_name='country',
        ),
    ]
