# Generated by Django 4.1.7 on 2023-03-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoveeregistrationtwo', '0005_rename_county_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
