# Generated by Django 4.1.7 on 2023-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoveeregistrationtwo', '0006_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
